GET http://localhost:5001/api/contacts


# POST http://localhost:5001/api/contacts
# Content-Type: application/json

# {
#   "name": "John Doe",
#   "email": "j.doe@gmail.com",
#   "phone": "1234567890"
# }

# PUT http://localhost:5001/api/contacts/123

# GET http://localhost:5001/api/contacts/123

# DELETE http://localhost:5001/api/contacts/6888ebc1f75f46fcae87327b

